inherit_from:
  - config/rubocop/rules_due_to_warning.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "spec/spec_helper.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "app/graphql/backend_schema.rb"
    - "app/controllers/graphql_controller.rb"
  Include:
    - rubocop-rspec

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false
Lint/OrAssignmentToConstant:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/HashSyntax:
  Enabled: true
Style/AccessorGrouping:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MapToHash:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/NegatedIf:
  Enabled: false

Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Naming/VariableNumber:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
