version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${ECR_REPO_URI}
  build:
    commands:
      - echo Building the Docker image...
      - cd backend
      - docker build
        -t ${ECR_REPO_URI}:${IMAGE_TAG}
        -f buildOnEcs/Dockerfile .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPO_URI}:${IMAGE_TAG}
