name: backendのCD(レビュー用)

on:
  push:

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call ci webhook
        shell: bash
        env:
          JENKINS_URL: ${{ vars.CI_JENKINS_URL }}
          JENKINS_JOB_URL: ${{ vars.CI_JENKINS_NANITABE_BUILD_TOKEN }}
          JENKINS_BUILD_TOKEN: ${{ secrets.JENKINS_BUILD_TOKEN }}
          # 必要なら GitHub Variables にしてもOK
          JENKINS_DEBUG: "false"
        run: |
          set -euo pipefail

          COOKIE_JAR="$(mktemp)"

          if [ "${JENKINS_DEBUG}" = "true" ]; then
            echo "Debug enabled"
          fi

          # CSRF対策の crumb を取得
          CRUMB_HEADER="$(
            curl -fsS -c "$COOKIE_JAR" "${JENKINS_URL%/}/crumbIssuer/api/json" \
            | python - <<'PY'
              import json,sys
              d=json.load(sys.stdin)
              print(f'{d["crumbRequestField"]}: { d[ "crumb" ] }')
              PY
          )"

          if [ "${JENKINS_DEBUG}" = "true" ]; then
          curl -i -sS --show-error -X POST \
          -b "$COOKIE_JAR" \
          -H "$CRUMB_HEADER" \
          "${JENKINS_JOB_URL%/}/build?token=${JENKINS_BUILD_TOKEN}" \
          -o -
          else
          curl -fsS -X POST \
          -b "$COOKIE_JAR" \
          -H "$CRUMB_HEADER" \
          "${JENKINS_JOB_URL%/}/build?token=${JENKINS_BUILD_TOKEN}"
          fi
