# バックエンド側の簡易的なCDワークフロー
# - ciサーバに設定をめちゃめちゃ書き込ませたくないから、git pull だけやらせる
# - 複雑になるなら、github actions側で多くをやるか、CodeBuildとかに移行する
name: Backend Deploy

#on:
#  pull_request:
#    types: [closed]

# デバッグ時
on:
  push:

jobs:
  call-url:
#    if: >
#      github.event.pull_request.merged == true &&
#      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Call ci webhook
        shell: bash
        env:
          N8N_WORKFLOW_ORIGIN: ${{ secrets.N8N_WORKFLOW_ORIGIN }}
          N8N_WORKFLOW_TOKEN: ${{ secrets.N8N_WORKFLOW_TOKEN_OF_NANITABE_BACKEND_DEPLOY }}
        run: |
          curl -X GET "${N8N_WORKFLOW_ORIGIN}/webhook/${N8N_WORKFLOW_TOKEN}"
