name: CI Backend Rubocop

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend-rubocop.yml'

jobs:
  backend-rubocop:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      BUNDLE_WITHOUT: "development:production"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.8'
          working-directory: backend
          bundler-cache: true

      - name: Run Rubocop
        working-directory: backend
        run: bundle exec rubocop
