name: CI Frontend Test

on:
  pull_request:

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect frontend changes
        id: changes
        run: |
          BASE_REF="${{ github.base_ref }}"

          echo "Base ref: $BASE_REF"

          BASE_SHA=$(git merge-base HEAD "origin/$BASE_REF")

          echo "BASE_SHA: $BASE_SHA"

          CHANGED_FILES="$(git diff --name-only "$BASE_SHA"...HEAD || true)"

          echo "Changed files:"
          echo "$CHANGED_FILES"

          if echo "$CHANGED_FILES" | grep -E '^frontend/|^\.github/workflows/ci-frontend-test\.yml$' > /dev/null; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: No backend changes, skip tests
        if: steps.changes.outputs.changed == 'false'
        run: |
          echo "No frontend changes. Skipping action."

      - name: Setup Node.js
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '24.11.1'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Install dependencies
        if: steps.changes.outputs.changed == 'true'
        run: yarn install --frozen-lockfile

      - name: Run tests
        if: steps.changes.outputs.changed == 'true'
        run: yarn test
